2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_setup.py:_flush():71] setting env: {}
2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_init.py:_log_setup():371] Logging user logs to H:\PROJECT\PYTHON\FGVSR\wandb\run-20220202_155017-2uc3detr\logs\debug.log
2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_init.py:_log_setup():372] Logging internal logs to H:\PROJECT\PYTHON\FGVSR\wandb\run-20220202_155017-2uc3detr\logs\debug-internal.log
2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_init.py:init():404] calling init triggers
2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-02 15:50:17,681 INFO    MainThread:23616 [wandb_init.py:init():449] starting backend
2022-02-02 15:50:17,682 INFO    MainThread:23616 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2022-02-02 15:50:17,685 INFO    MainThread:23616 [backend.py:ensure_launched():199] starting backend process...
2022-02-02 15:50:17,934 INFO    MainThread:23616 [backend.py:ensure_launched():204] started backend process with pid: 1904
2022-02-02 15:50:17,934 INFO    MainThread:23616 [wandb_init.py:init():458] backend started and connected
2022-02-02 15:50:17,935 INFO    MainThread:23616 [wandb_init.py:init():519] updated telemetry
2022-02-02 15:50:17,936 INFO    MainThread:23616 [wandb_init.py:init():549] communicating current version
2022-02-02 15:50:19,070 INFO    MainThread:23616 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-02 15:50:19,070 INFO    MainThread:23616 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-02 15:50:19,499 INFO    MainThread:23616 [wandb_init.py:init():592] starting run threads in backend
2022-02-02 15:50:21,756 WARNING MainThread:23616 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "H:\APP\Anaconda\envs\a\lib\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "H:\APP\Anaconda\envs\a\lib\site-packages\wandb\sdk\wandb_init.py", line 597, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "H:\APP\Anaconda\envs\a\lib\site-packages\wandb\sdk\interface\interface.py", line 216, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "H:\APP\Anaconda\envs\a\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 446, in _communicate_run_start
    result = self._communicate(rec)
  File "H:\APP\Anaconda\envs\a\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "H:\APP\Anaconda\envs\a\lib\site-packages\wandb\sdk\interface\router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "H:\APP\Anaconda\envs\a\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "H:\APP\Anaconda\envs\a\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
